// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLTo_E01ROa-sbwwB5bJR4VI6JwQJsLw',
    appId: '1:158104651494:web:47bdc63bd6a29cd4a09d27',
    messagingSenderId: '158104651494',
    projectId: 'recrutement-9cdab',
    authDomain: 'recrutement-9cdab.firebaseapp.com',
    storageBucket: 'recrutement-9cdab.firebasestorage.app',
    measurementId: 'G-6H2BQDC6ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfo_mkYQRRMvkTdLxGANJ86Vi969w01o',
    appId: '1:158104651494:android:db69b0ae246f7190a09d27',
    messagingSenderId: '158104651494',
    projectId: 'recrutement-9cdab',
    storageBucket: 'recrutement-9cdab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8wcxYuH_LdMIEy6EAObOy8giHq2xecg',
    appId: '1:158104651494:ios:f432f6def34eb821a09d27',
    messagingSenderId: '158104651494',
    projectId: 'recrutement-9cdab',
    storageBucket: 'recrutement-9cdab.firebasestorage.app',
    iosBundleId: 'com.example.applicationDeRecrutement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD8wcxYuH_LdMIEy6EAObOy8giHq2xecg',
    appId: '1:158104651494:ios:f432f6def34eb821a09d27',
    messagingSenderId: '158104651494',
    projectId: 'recrutement-9cdab',
    storageBucket: 'recrutement-9cdab.firebasestorage.app',
    iosBundleId: 'com.example.applicationDeRecrutement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyLTo_E01ROa-sbwwB5bJR4VI6JwQJsLw',
    appId: '1:158104651494:web:11e020d74585aa60a09d27',
    messagingSenderId: '158104651494',
    projectId: 'recrutement-9cdab',
    authDomain: 'recrutement-9cdab.firebaseapp.com',
    storageBucket: 'recrutement-9cdab.firebasestorage.app',
    measurementId: 'G-9SWKTS9ENP',
  );
}
